#! /bin/bash

if [ `uname` == "Linux" ]; then
    DB_DIR="/mnt/MYUSB/NGenDB/DATA"
elif [ `uname` == "Darwin" ]; then
    DB_DIR="/Volumes/MYUSB/NGenDB/DATA"
fi

DB_PORT=5555

./mongod --dbpath $DB_DIR --port $DB_PORT
